version: '3.8'

services:
  discord-bot:
    image: kdidtech/discord-todo-bot:latest
    environment:
      - DISCORD_BOT_TOKEN=your-discord-bot-token-here
    volumes:
      - ./data/:/app/data/
    restart: always
